language: cpp

compiler:
  - gcc
  - clang

notifications:
  email: false

before_install:
  - sudo apt-get install libboost-dev

before_script: 
  - cd hw01-cli
  - mkdir build
  - cd build

script:
  - cmake ..
  - make
  - ./test/pipe_tokenizer_tests

after_script: 
  - cd .. 
  - rm -rf build

matrix:
  includes:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libboost-all-dev
