jobs:

- job: buildLinuxCLI
  displayName: Build CLI for Linux
  pool:
    vmImage: ubuntu-18.04
  steps:
    - script: |
        sudo apt-get install libboost-dev

        export CC=gcc-7
        export CXX=g++-7

        mkdir build
        cd build
        cmake ..
        make
        
        cd test
        ./hw01_cli_tests

      workingDirectory: 'hw01-cli'