jobs:

- job: buildLinuxCLI
  displayName: Build CLI for Linux
  pool:
    vmImage: ubuntu-18.04
  steps:
    - script: |
        git submodule init
    - script: |
        ls -lh
        # mkdir build
        # cd build
        # cmake ..
        # make
        
        # cd test
        # ./hw01-cli

      workingDirectory: 'hw01-cli'

- job: buildWindowsCLI
  displayName: Build CLI for Windows
  pool:
    vmImage: windows-2019
  steps:
    - script: |
        git submodule init
    - script: |
        mkdir build
        cd build
        cmake ..
        make
        
        cd test
        ./hw01-cli

      workingDirectory: 'hw01-cli'