pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: ShellScript@2
  inputs:
    scriptPath: 'build.sh'
  displayName: 'Run build script'

- script: |
    cd build/test/
    ./hw01_cli_tests
  displayName: 'Run tests'
