jobs:

- job: buildLinuxCLI
  displayName: Build CLI for Linux
  pool:
    vmImage: ubuntu-18.04
  steps:
    - script: |
        mkdir build
        cd build
        cmake ..
        make
        
        cd test
        ./hw01-cli

      workingDirectory: 'hw01-cli'