pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    pwd
# - task: ShellScript@2
#   inputs:
#     scriptPath: 'hw01-cli/build.sh'
#   displayName: 'Run build script'

# - script: |
#     cd build/test/
#     ./hw01_cli_tests
#   displayName: 'Run tests'
