jobs:

- job: buildLinuxCLI
  displayName: Build CLI for Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - bash: 'ls -lh'
      workingDirectory: 'hw01-cli'

# steps:
# # - task: Bash@3
# #   inputs:
# #     workingDirectory: 'hw01-cli'
# #     scriptPath: 'build.sh'
# #   displayName: 'Run build script'

# # - script: |
# #     cd build/test/
# #     ./hw01_cli_tests
# #   displayName: 'Run tests'


# - script: |
#     cd hw01-cli/
#     bash build.sh
#     ls -lh