jobs:

- job: buildLinuxCLI
  displayName: Build CLI for Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - bash: './build.sh'
      workingDirectory: 'hw01-cli'
      displayName: Build
    - bash: './run_tests.sh'
      workingDirectory: 'hw01-cli'
      displayName: Run tests
