jobs:

- job: buildLinuxCLI
  displayName: Build CLI for Linux
  pool:
    vmImage: ubuntu-18.04
  steps:
    - checkout: self
      submodules: recursive
    - script: |

        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt -y update
        sudo apt install g++-9 ninja-build -y
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install zlib openssl boost-system boost-date-time boost-regex websocketpp boost-thread boost-filesystem boost-random boost-chrono boost-interprocess brotli --vcpkg-root ./vcpkg


        mkdir build
        cd build
        cmake ..
        make
        
        cd test
        ./hw01_li_test

      workingDirectory: 'hw01-cli'

- job: buildWindowsCLI
  displayName: Build CLI for Windows
  pool:
    vmImage: windows-2019
  steps:
    - checkout: self
      submodules: recursive
    - script: |
        mkdir build
        cd build
        ccmake ..
        make
        
        cd test
        hw01_cli_test

      workingDirectory: 'hw01-cli'